server:
  port: 8761
  servlet:
    context-path: /service-discovery
spring:
  application:
    name: service-discovery
  cloud:
    config:
      server:
          clone-on-start: true
          default-label: main
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://localhost:8761
  instance:
    hostname: localhost