server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/auth_pdb
    username: system
    password: oracle123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

jwt:
  secret: UniversityManagementSuperSecureSecretKeyForJWTTokenGeneration2024ThatIsVeryLongAndSecureEnoughForHS512Algorithm
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.university: INFO
  file:
    name: logs/auth-service.log